const detailAccount = [
  // {
  //   email: "dwidaya_admin2@daisi.id",
  //   password: "Balidays123!",
  //   branch: "Dwidaya Tour Pacific Place",
  //   sender: "02DWIDAY",
  //   phone: 628111142740,
  // },
  // {
  //   email: "dwidaya_admin3@daisi.id",
  //   password: "Balidays123!",
  //   branch: "Dwidayatour Emporium",
  //   sender: "03DWIDAY",
  //   phone: 628111142694,
  // },
  // {
  //   email: "dwidaya_admin4@daisi.id",
  //   password: "Balidays123!",
  //   branch: "DwidayaTour Hayam Wuruk",
  //   sender: "04DWIDAY",
  //   phone: 628111142715,
  // },
  // {
  //   email: "dwidaya_admin5@daisi.id",
  //   password: "Balidays123!",
  //   branch: "DwidayaTour Menara Astra",
  //   sender: "05DWIDAY",
  //   phone: 628111142698,
  // },
  // {
  //   email: "dwidaya_admin6@daisi.id",
  //   password: "Balidays123!",
  //   branch: "DwidayaTour Menara Imperium",
  //   sender: "06DWIDAY",
  //   phone: 628111142696,
  // },
  // {
  //   email: "dwidaya_admin7@daisi.id",
  //   password: "Balidays123!",
  //   branch: "Dwidaya Tour Mal Ciputra Cibubur",
  //   sender: "07DWIDAY",
  //   phone: 628111142734,
  // },
  // {
  //   email: "dwidaya_admin8@daisi.id",
  //   password: "Balidays123!",
  //   branch: "Dwidaya Tour Taman Anggrek",
  //   sender: "08DWIDAY",
  //   phone: 6282128703109,
  // },
  // {
  //   email: "dwidaya_admin9@daisi.id",
  //   password: "Balidays123!",
  //   branch: "Dwidaya Tour Mangga Dua",
  //   sender: "09DWIDAY",
  //   phone: 62811876411,
  // },
  // {
  //   email: "dwidaya_admin12@daisi.id",
  //   password: "Balidays123!",
  //   branch: "Dwidaya Tour Centre Point Medan",
  //   sender: "12DWIDAY",
  //   phone: 6281269617262,
  // },
  // {
  //   email: "dwidaya_admin13@daisi.id",
  //   password: "Balidays123!",
  //   branch: "Dwidaya Tour Balikpapan",
  //   sender: "13DWIDAY",
  //   phone: 6282252724117,
  // },
  // {
  //   email: "dwidaya_admin14@daisi.id",
  //   password: "Balidays123!",
  //   branch: "Dwidaya Tour Palembang Icon",
  //   sender: "14DWIDAY",
  //   phone: 628111142820,
  // },
  // {
  //   email: "dwidaya_admin15@daisi.id",
  //   password: "Balidays123!",
  //   branch: "Dwidaya Tour Big Mal Samarinda",
  //   sender: "15DWIDAY",
  //   phone: 6281350752022,
  // },
  // {
  //   email: "dwidaya_admin16@daisi.id",
  //   password: "Balidays123!",
  //   branch: "Dwidaya Tour Mal Jayapura",
  //   sender: "16DWIDAY",
  //   phone: 6282123626809,
  // },
  // {
  //   email: "dwidaya_admin17@daisi.id",
  //   password: "Balidays123!",
  //   branch: "Dwidaya Tour Manado Town Square",
  //   sender: "17DWIDAY",
  //   phone: 628111142932,
  // },
  // {
  //   email: "dwidaya_admin18@daisi.id",
  //   password: "Balidays123!",
  //   branch: "Dwidaya Tour Bali Teuku Umar ",
  //   sender: "18DWIDAY",
  //   phone: 628111162521,
  // },
  // {
  //   email: "dwidaya_admin19@daisi.id",
  //   password: "Balidays123!",
  //   branch: "Nusantara Tour DP Mal Semarang",
  //   sender: "19DWIDAY",
  //   phone: 628112842880,
  // },
  // {
  //   email: "dwidaya_admin20@daisi.id",
  //   password: "Balidays123!",
  //   branch: "Nusantara Tour Puri",
  //   sender: "20DWIDAY",
  //   phone: 628112842877,
  // },
  // {
  //   email: "dwidaya_admin21@daisi.id",
  //   password: "Balidays123!",
  //   branch: "Nusantara Tour Purwokerto",
  //   sender: "21DWIDAY",
  //   phone: 628112935588,
  // },
  // {
  //   email: "dwidaya_admin22@daisi.id",
  //   password: "Balidays123!",
  //   branch: "Nusantara Tour Salatiga",
  //   sender: "22DWIDAY",
  //   phone: 628112704887,
  // },
  // {
  //   email: "dwidaya_admin23@daisi.id",
  //   password: "Balidays123!",
  //   branch: "Nusantara Tour UNS",
  //   sender: "23DWIDAY",
  //   phone: 628112689578,
  // },
  // {
  //   email: "dwidaya_admin24@daisi.id",
  //   password: "Balidays123!",
  //   branch: "Nusantara Tour Tembalang",
  //   sender: "24DWIDAY",
  //   phone: 628112663037,
  // },
  // {
  //   email: "dwidaya_admin26@daisi.id",
  //   password: "Balidays123!",
  //   branch: "Nusantara Tour Temanggung",
  //   sender: "26DWIDAY",
  //   phone: 628112525388,
  // },
  // {
  //   email: "dwidaya_admin27@daisi.id",
  //   password: "Balidays123!",
  //   branch: "Dwidaya Tour Central Park",
  //   sender: "27DWIDAY",
  //   phone: 6282122927708,
  // },
  // {
  //   email: "dwidaya_admin28@daisi.id",
  //   password: "Balidays123!",
  //   branch: "Dwidaya Tour Mall Bintarojaya Xchange",
  //   sender: "28DWIDAY",
  //   phone: 6282268688860,
  // },
  // {
  //   email: "dwidaya_admin29@daisi.id",
  //   password: "Balidays123!",
  //   branch: "Dwidaya Tour Aeon Mall",
  //   sender: "29DWIDAY",
  //   phone: 628111142736,
  // },
  // {
  //   email: "dwidaya_admin30@daisi.id",
  //   password: "Balidays123!",
  //   branch: "Dwidaya Tour Pantai Indah Kapuk",
  //   sender: "30DWIDAY",
  //   phone: 6282112956048,
  // },
  // {
  //   email: "dwidaya_admin31@daisi.id",
  //   password: "Balidays123!",
  //   branch: "Dwidaya Tour Grand Indonesia",
  //   sender: "31DWIDAY",
  //   phone: 6281294799710,
  // },
  // {
  //   email: "dwidaya_admin32@daisi.id",
  //   password: "Balidays123!",
  //   branch: "Dwidaya Tour Mal Pondok Indah",
  //   sender: "32DWIDAY",
  //   phone: 6281319149911,
  // },
  // {
  //   email: "dwidaya_admin33@daisi.id",
  //   password: "Balidays123!",
  //   branch: "Dwidaya Tour Kemang Village",
  //   sender: "33DWIDAY",
  //   phone: 628111142693,
  // },
  {
    email: "dwidaya_admin34@daisi.id",
    password: "Balidays123!",
    branch: "Dwidaya Tour Pakuwon Surabaya",
    sender: "34DWIDAY",
    phone: 6282131586670,
  },
  {
    email: "dwidaya_admin35@daisi.id",
    password: "Balidays123!",
    branch: "Dwidaya Tour Kelapa Gading",
    sender: "35DWIDAY",
    phone: 628118203405,
  },
  // {
  //   email: "dwidaya_admin36@daisi.id",
  //   password: "Balidays123!",
  //   branch: "Dwidaya Tour Mal Puri",
  //   sender: "36DWIDAY",
  //   phone: 628111142726,
  // },
  // {
  //   email: "dwidaya_admin37@daisi.id",
  //   password: "Balidays123!",
  //   branch: "Dwidaya Tour Sumarecon Mall Serpong",
  //   sender: "37DWIDAY",
  //   phone: 6281296697321,
  // },
  // {
  //   email: "dwidaya_admin38@daisi.id",
  //   password: "Balidays123!",
  //   branch: "Dwidaya Tour Ayani Megamall Pontianak",
  //   sender: "38DWIDAY",
  //   phone: 6281256158770,
  // },
  // {
  //   email: "dwidaya_admin39@daisi.id",
  //   password: "Balidays123!",
  //   branch: "Dwidaya Tour Bandung",
  //   sender: "39DWIDAY",
  //   phone: 6281119059963,
  // },
  // {
  //   email: "dwidaya_admin40@daisi.id",
  //   password: "Balidays123!",
  //   branch: "Dwidaya Tour Samanhudi",
  //   sender: "40DWIDAY",
  //   phone: 628111142725,
  // },
  // {
  //   email: "dwidaya_admin41@daisi.id",
  //   password: "Balidays123!",
  //   branch: "Dwidaya Tour Senayan City",
  //   sender: "41DWIDAY",
  //   phone: 628111142953,
  // },
  {
    email: "dwidaya_admin42@daisi.id",
    password: "Balidays123!",
    branch: "Dwidaya Tour Duta Mall Banjarmasin",
    sender: "42DWIDAY",
    phone: 6281119059965,
  },
  {
    email: "dwidaya_admin43@daisi.id",
    password: "Balidays123!",
    branch: "Dwidaya Tour Living World Pekanbaru",
    sender: "43DWIDAY",
    phone: 628111142761,
  },
  // {
  //   email: "dwidaya_admin44@daisi.id",
  //   password: "Balidays123!",
  //   branch: "Dwidaya Tour Trans Studio Makasar",
  //   sender: "44DWIDAY",
  //   phone: 6281119059967,
  // },
  // {
  //   email: "dwidaya_admin45@daisi.id",
  //   password: "Balidays123!",
  //   branch: "Nusantara Tour Simpanglima",
  //   sender: "45DWIDAY",
  //   phone: 6281391328112,
  // },
  // {
  //   email: "dwidaya_admin46@daisi.id",
  //   password: "Balidays123!",
  //   branch: "Nusantara Tour Besen",
  //   sender: "46DWIDAY",
  //   phone: 6281119041802,
  // },
  // {
  //   email: "dwidaya_admin47@daisi.id",
  //   password: "Balidays123!",
  //   branch: "Nusantara Tour Hartonomall",
  //   sender: "47DWIDAY",
  //   phone: 6281119041803,
  // },
  // {
  //   email: "dwidaya_admin48@daisi.id",
  //   password: "Balidays123!",
  //   branch: "Nusantara Tour Solo",
  //   sender: "48DWIDAY",
  //   phone: 6281119041804,
  // },
  // {
  //   email: "dwidaya_admin49@daisi.id",
  //   password: "Balidays123!",
  //   branch: "Dwidaya Tour Karawaci",
  //   sender: "49DWIDAY",
  //   phone: 6281310576385,
  // },
  // {
  //   email: "dwidaya_admin50@daisi.id",
  //   password: "Balidays123!",
  //   branch: "Dwidaya Tour WTCII",
  //   sender: "50DWIDAY",
  //   phone: 628111142746,
  // },
  // {
  //   email: "dwidaya_admin51@daisi.id",
  //   password: "Balidays123!",
  //   branch: "Dwidaya Tour Kota Kasablanka",
  //   sender: "51DWIDAY",
  //   phone: 628119511893,
  // },
  // {
  //   email: 'aris.hasiholan@smailingtour.co.id',
  //   password: 'Smailing123!',
  // },
  // {
  //   email: 'marcomm@smailingtour.co.id',
  //   password: 'Smailing123!',
  // },
  // {
  //   email: 'catur@smailingtour.co.id',
  //   password: 'Smailing123!',
  // },
  // {
  //   email: 'vip@smailingtour.co.id',
  //   password: 'Smailing123!',
  // },
];

export default detailAccount;
